### ISSUE TITLE
Test for dyadic rationals reports error

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/twenty-first#151]
This error happens stochastically, about once every five to ten test run. The failing test is `amount::dyadic_rationals::dyadic_rationals_tests::add_sub_pbt`.

```
failures:

---- amount::dyadic_rationals::dyadic_rationals_tests::add_sub_pbt stdout ----
thread 'amount::dyadic_rationals::dyadic_rationals_tests::add_sub_pbt' panicked at twenty-first/src/amount/dyadic_rationals.rs:155:9:
Right-hand-side argument cannot be larger than left-hand-side for subtraction
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: <twenty_first::amount::dyadic_rationals::DyadicRational as core::ops::arith::Sub>::sub
             at ./src/amount/dyadic_rationals.rs:155:9
   3: twenty_first::amount::dyadic_rationals::dyadic_rationals_tests::add_sub_pbt
             at ./src/amount/dyadic_rationals.rs:341:37
   4: twenty_first::amount::dyadic_rationals::dyadic_rationals_tests::add_sub_pbt::{{closure}}
             at ./src/amount/dyadic_rationals.rs:336:22
   5: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    amount::dyadic_rationals::dyadic_rationals_tests::add_sub_pbt

test result: FAILED. 407 passed; 1 failed; 4 ignored; 0 measured; 0 filtered out; finished in 7.51s

error: test failed, to rerun pass `-p twenty-first --lib`
make: *** [Makefile:63: test] Error 101
```

**Comment by Sword-Smith** [comment]
Some debugging output. I suspect the problem liens with the `Ordering` implementation, the implementation that allows the use of greater/less than `>`/`<`.

```
DyadicRational { mantissa: 12516635689082565772, exponent: 4 } + DyadicRational { mantissa: 1171144540130836136, exponent: 3 } = DyadicRational { mantissa: 3714731192336059511, exponent: 2 }
thread 'amount::dyadic_rationals::dyadic_rationals_tests::add_sub_pbt' panicked at twenty-first/src/amount/dyadic_rationals.rs:155:9:
Right-hand-side argument cannot be larger than left-hand-side for subtraction.
LHS was: DyadicRational { mantissa: 3714731192336059511, exponent: 2 },
RHS: DyadicRational { mantissa: 12516635689082565772, exponent: 4 }

```
